change file

diff --git a/debian/wine-devel.postinst b/debian/wine-devel.postinst
--- a/debian/wine-devel.postinst
+++ b/debian/wine-devel.postinst
@@ -14,14 +14,14 @@ case "$1" in
 
             # Allow dpkg-reconfigure to remove caps
             if test "$RET" = "true"; then
-                if ! setcap "cap_net_raw=epi" /opt/wine-devel/bin/wineserver; then
-                   echo "Setcap failed on /opt/wine-devel/bin/wineserver, applications that need to send/receive raw IP packets will not work" >&2
+                if ! setcap "cap_net_raw=epi" /opt/spark-wine8/bin/wineserver; then
+                   echo "Setcap failed on /opt/spark-wine8/bin/wineserver, applications that need to send/receive raw IP packets will not work" >&2
                 fi
             else
                 # setcap -r fails if the xattr is not present
-                if getcap /opt/wine-devel/bin/wineserver | grep -qs "/opt/wine-devel/bin/wineserver"; then
-                    if ! setcap "-r" /opt/wine-devel/bin/wineserver; then
-                       echo "Setcap -r failed on /opt/wine-devel/bin/wineserver, could not remove capabilities" >&2
+                if getcap /opt/spark-wine8/bin/wineserver | grep -qs "/opt/spark-wine8/bin/wineserver"; then
+                    if ! setcap "-r" /opt/spark-wine8/bin/wineserver; then
+                       echo "Setcap -r failed on /opt/spark-wine8/bin/wineserver, could not remove capabilities" >&2
                     fi
                 fi
             fi
